### ISSUE TITLE
Internal error on task submission (clean install, tutorial course)

### ISSUE THREAD

**Issue by zootos** [UCL-INGI/INGInious#524]
Installing INGInious version 0.6 on a clean Ubuntu 18.04.4 LTS installation, following the provided [installation guide](https://inginious.readthedocs.io/en/v0.6/install_doc/installation.html) with all defaults selected when running `inginious-install`, results in most of the tasks in the [tutorial course](https://github.com/UCL-INGI/INGInious-demo-tasks) producing internal errors when ran. The only tasks not failing are the three tasks using the `mcq` environement. For the remaining tasks, the following error is given in the web interface:

```
An internal error occurred. Please retry later. If the error persists, send an email to the course administrator. [Submission #5eb3da069949682704d3cb19]
The grader did not return a readable output : 'NoneType' object has no attribute 'items'
```

Based on the log, the code that crashes seems to lie on line 574 in `inginious/agent/docker_agent/__init__.py`.  Based on my probing of the problem, it seems like there is something wrong with the `ingi/inginious-c-base` docker container.

### Steps to reproduce:

1. Install Ubuntu 18.04 LTS on a machine, VM or similar
2. Follow the installation guide for version 0.6 of INGInious
3. In the tutorial course, try to submit task 1 with the content `print("Hello World!")`

**Comment by zootos** [comment]
If it helps with debugging, I can add that the problem was discovered when working on a setup, using version 0.5, that has an installation script that work perfectly fine in November 2019 and has not been changed since then. I do realize that there is only two versions (dev and latest) of the docker containers, and that the **lastest**-version is the one meant for version 0.6. Updating the setup to version 0.6 resulted in the same error both for the tutorial course and the course we used INGInious during the fall of 2019.

**Comment by anthonygego** [comment]
Are you able to perform a ``docker logs`` on the container ?

I'm wondering if this could be due to the msgpack update and a possible version mismatch. Version 1.0 contains breaking changes. Did you downloaded the container from docker hub ? If this is the case, can you try building the two base containers from the v0.6 branch of the repo, ensuring the msgpack version that is used is below 1.0 ?

Maybe you'll have to change https://github.com/UCL-INGI/INGInious/blob/master/base-containers/base/Dockerfile#L15 to tell msgpack-python==0.5.6

**Comment by zootos** [comment]
I am not able to perform a docker logs on the container. The container instance seems to be immediately killed, and it seems like the logs disappear when you kill the instance?

I downloaded the containers from docker hub (docker pull) originally. I have now removed these, and built the containers from the v0.6 branch of the repo, with the suggested change to the Dockerfile. I have accessed both of them using `docker run -t -i <container-name> /bin/bash`, and found that the version of `msgpack-python` is `0.5.6` in both of them. The problem still remains.

I have attached the relevant part of the INGInious logs, in case that helps.

```
2020-05-07 14:51:43,093 - inginious.backend - INFO - Adding a new job b'\x00Q_\x00|' 47572435-de91-411d-a2c4-8fb0c72f2a38 to the queue
2020-05-07 14:51:43,093 - inginious.backend - INFO - Sending job b'\x00Q_\x00|' 47572435-de91-411d-a2c4-8fb0c72f2a38 to agent b'\x00y\xe2\xa9\xe4'
2020-05-07 14:51:43,093 - inginious.agent.docker - INFO - Received request for jobid (b'\x00Q_\x00|', '47572435-de91-411d-a2c4-8fb0c72f2a38')
2020-05-07 14:51:43,093 - inginious.agent.docker - INFO - Received request for jobid (b'\x00Q_\x00|', '47572435-de91-411d-a2c4-8fb0c72f2a38')
2020-05-07 14:51:43,093 - inginious.webapp.submissions - INFO - New submission from superadmin - superadmin@inginious.org - tutorial/01_getting_started - 127.0.0.1
2020-05-07 14:51:43,096 - inginious.webapp.requests - INFO - 127.0.0.1:45074 - "HTTP/1.1 POST /course/tutorial/01_getting_started" - 200 OK
2020-05-07 14:51:43,775 - inginious.agent.docker - WARNING - Container c336f46a6d9acf596963a28d613cb3af9d28228e4ec503db33ea95d56d818f9c has not given any result
2020-05-07 14:51:43,776 - inginious.agent.docker - ERROR - Cannot get back output of container c336f46a6d9acf596963a28d613cb3af9d28228e4ec503db33ea95d56d818f9c! ('NoneType' object has no attribute 'items')
Traceback (most recent call last):
  File "/home/neo/.local/lib/python3.6/site-packages/inginious/agent/docker_agent/__init__.py", line 574, in handle_job_closing
    for key, item in return_value.items():
AttributeError: 'NoneType' object has no attribute 'items'
2020-05-07 14:51:43,794 - inginious.backend - INFO - Job b'\x00Q_\x00|' 47572435-de91-411d-a2c4-8fb0c72f2a38 finished on agent b'\x00y\xe2\xa9\xe4'
2020-05-07 14:51:44,165 - inginious.webapp.requests - INFO - 127.0.0.1:45074 - "HTTP/1.1 POST /course/tutorial/01_getting_started" - 200 OK
```

**Comment by zootos** [comment]
My bad. It seems like I did something wrong when testing your suggested change yesterday. I tried rebuilding everything from the bottom up today, using the suggested change. The tasks will now run fine when specifying that the version of `msgpack-python` as `<1.0`. I have made a PR (#525) to put these changes into the v0.6 branch.
